#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [2]:
np.version.version

'1.17.4'

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
np.random.random((2,3,5))

array([[[0.04296841, 0.07688664, 0.38012297, 0.96899419, 0.46622267],
        [0.18801191, 0.09004764, 0.89332619, 0.06175773, 0.33474829],
        [0.9850194 , 0.15765043, 0.73785673, 0.31084989, 0.03199508]],

       [[0.14553244, 0.31405264, 0.59491227, 0.81220687, 0.00804607],
        [0.49843224, 0.1515062 , 0.63153383, 0.57385335, 0.20518193],
        [0.79887934, 0.79766905, 0.74023768, 0.57404155, 0.06140747]]])

In [4]:
np.random.rand(2,3,5)

array([[[0.06778661, 0.44813024, 0.48486456, 0.36279628, 0.84499622],
        [0.50523401, 0.44785429, 0.3473876 , 0.11242953, 0.44362024],
        [0.74255617, 0.07542213, 0.22248953, 0.21915965, 0.14177695]],

       [[0.31915419, 0.82966974, 0.16837848, 0.59508299, 0.62049529],
        [0.07170454, 0.34555782, 0.74770639, 0.97346447, 0.14367179],
        [0.48229422, 0.57710738, 0.83345652, 0.82796427, 0.83346846]]])

In [5]:
a = np.random.randint(10, size=(2,3,5))

#4. Print a.

In [6]:
print(a)

[[[6 4 9 1 7]
  [0 9 7 7 5]
  [9 5 7 3 7]]

 [[8 0 7 3 8]
  [7 0 8 3 2]
  [3 1 9 2 5]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [7]:
b = np.ones((5,2,3))

#6. Print b.

In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [9]:
a.size == b.size

True

#8. Are you able to add a and b? Why or why not?

In [10]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [11]:
c = np.transpose(b,(1,2,0))

In [12]:
print(a.shape, c.shape)

(2, 3, 5) (2, 3, 5)


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [13]:
d = np.add(a, c)
# because has the same shape
print(d)

[[[ 7.  5. 10.  2.  8.]
  [ 1. 10.  8.  8.  6.]
  [10.  6.  8.  4.  8.]]

 [[ 9.  1.  8.  4.  9.]
  [ 8.  1.  9.  4.  3.]
  [ 4.  2. 10.  3.  6.]]]


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print("array A")
print(a)
print("array D")
print(d)

array A
[[[6 4 9 1 7]
  [0 9 7 7 5]
  [9 5 7 3 7]]

 [[8 0 7 3 8]
  [7 0 8 3 2]
  [3 1 9 2 5]]]
array D
[[[ 7.  5. 10.  2.  8.]
  [ 1. 10.  8.  8.  6.]
  [10.  6.  8.  4.  8.]]

 [[ 9.  1.  8.  4.  9.]
  [ 8.  1.  9.  4.  3.]
  [ 4.  2. 10.  3.  6.]]]


#12. Multiply a and c. Assign the result to e.

In [15]:
e = np.multiply(a,c)

#13. Does e equal to a? Why or why not?

In [16]:
a == e
# because we multiply by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [17]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"Max value {d_max}, Min value {d_min}, Mean value {d_mean}")

Max value 10.0, Min value 1.0, Mean value 6.066666666666666


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [18]:
'''
np.empty does NOT provide an array with zero or no value
it provides an array with arbitrary values (not very random, though)
'''

f = np.empty((2, 3, 5), dtype=np.int8)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [19]:
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75
    else:
        f[it.multi_index] = 100
    it.iternext()
    
        

#17. Print d and f. Do you have your expected f?

In [20]:
print(d)
print(f)

[[[ 7.  5. 10.  2.  8.]
  [ 1. 10.  8.  8.  6.]
  [10.  6.  8.  4.  8.]]

 [[ 9.  1.  8.  4.  9.]
  [ 8.  1.  9.  4.  3.]
  [ 4.  2. 10.  3.  6.]]]
[[[ 75  25 100  25  75]
  [  0 100  75  75  25]
  [100  25  75  25  75]]

 [[ 75   0  75  25  75]
  [ 75   0  75  25  25]
  [ 25  25 100  25  25]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [21]:
g = np.empty((2, 3, 5), dtype=str)
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = 'A'
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = 'B'
    elif it[0] == d_mean:
        g[it.multi_index] = 'C'
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = 'D'
    else:
        g[it.multi_index] = 'E'
    it.iternext()

In [22]:
print(g)

[[['D' 'B' 'E' 'B' 'D']
  ['A' 'E' 'D' 'D' 'B']
  ['E' 'B' 'D' 'B' 'D']]

 [['D' 'A' 'D' 'B' 'D']
  ['D' 'A' 'D' 'B' 'B']
  ['B' 'B' 'E' 'B' 'B']]]
